"""영업관리 계정 CSV를 크롬 확장 계정 데이터로 내보낸다."""

from __future__ import annotations

import json
import logging

import pandas as pd

from modules.transform.utility.paths import COLLECTOR_EXT_DIR, LOCAL_DB

logger = logging.getLogger(__name__)

EMPLOYEE_CSV_PATH = LOCAL_DB / "영업관리부_DB" / "sales_employee.csv"
ACCOUNTS_DATA_PATH = COLLECTOR_EXT_DIR / "accounts_data.js"
OPEN_DATE_COLUMN = "실오픈일"

PLATFORM_MAP = {
    "배달의 민족": "baemin",
    "쿠팡이츠": "coupang",
    "요기요": "yogiyo",
    "땡겨요": "ddangyo",
}


def _clean_value(value: object) -> str:
    if pd.isna(value):
        return ""
    return str(value).strip()


def drop_unopened_stores(df: pd.DataFrame) -> tuple[pd.DataFrame, list[str]]:
    """실오픈일이 아직 오지 않은 매장을 수집 대상에서 제외한다.

    계정은 발급됐지만 매장이 열리지 않은 상태에서는 수집이 매번 실패하고 백필 큐만 쌓인다.
    sales_employee.csv 자체는 여러 파이프라인이 공유하는 매장 마스터라 건드리지 않고,
    크롬 확장이 읽는 accounts_data.js에서만 제외한다.
    """
    if OPEN_DATE_COLUMN not in df.columns:
        logger.warning("[계정 export] '%s' 컬럼 없음 — 미오픈 매장 제외 스킵", OPEN_DATE_COLUMN)
        return df, []

    today = pd.Timestamp.now(tz="Asia/Seoul").tz_localize(None).normalize()
    open_dt = pd.to_datetime(df[OPEN_DATE_COLUMN], errors="coerce")
    # 파싱 불가/공백은 유지한다(안전 측). 미래 오픈일만 제외.
    unopened = open_dt.notna() & (open_dt > today)
    if not unopened.any():
        return df, []

    excluded = sorted({_clean_value(name) for name in df.loc[unopened, "매장명"]} - {""})
    logger.info(
        "[계정 export] 미오픈 매장 제외 %d개 (%s > %s): %s",
        len(excluded), OPEN_DATE_COLUMN, today.strftime("%Y-%m-%d"), ", ".join(excluded),
    )
    return df[~unopened].copy(), excluded


def build_accounts_dict(df: pd.DataFrame) -> dict[str, list[dict[str, str]]]:
    """CSV DataFrame을 accounts.js 호환 dict로 변환한다."""
    required_columns = ["담당자", "매장명", "플랫폼", "계정ID", "계정PW"]
    missing = [column for column in required_columns if column not in df.columns]
    if missing:
        logger.warning("[계정 export] CSV 헤더 누락: %s", missing)
        return {}

    entry_map: dict[str, dict[str, str]] = {}
    for _, row in df.iterrows():
        manager = _clean_value(row["담당자"])
        store = _clean_value(row["매장명"])
        platform_label = _clean_value(row["플랫폼"])
        account_id = _clean_value(row["계정ID"])
        account_pw = _clean_value(row["계정PW"])
        platform = PLATFORM_MAP.get(platform_label)

        if not manager or not store or not platform or not account_id or not account_pw:
            continue

        key = f"{manager}|{store}|{platform}"
        entry_map[key] = {
            "manager": manager,
            "store": store,
            "platform": platform,
            "id": account_id,
            "pw": account_pw,
        }

    result: dict[str, list[dict[str, str]]] = {}
    for entry in entry_map.values():
        result.setdefault(entry["manager"], []).append(
            {
                "store": entry["store"],
                "platform": entry["platform"],
                "id": entry["id"],
                "pw": entry["pw"],
            }
        )

    for stores in result.values():
        stores.sort(key=lambda item: item["store"])

    return result


def _count_coupang_accounts(data: dict[str, list[dict[str, str]]]) -> int:
    return sum(
        1
        for stores in data.values()
        for account in stores
        if account.get("platform") == "coupang"
    )


def export_accounts_js() -> str:
    """CSV 읽기, dict 변환, accounts_data.js 저장 후 XCom 메시지를 반환한다."""
    df = pd.read_csv(EMPLOYEE_CSV_PATH, dtype=str, encoding="utf-8-sig")
    df, unopened_stores = drop_unopened_stores(df)
    data = build_accounts_dict(df)
    manager_count = len(data)
    coupang_count = _count_coupang_accounts(data)
    unopened_note = f" / 미오픈 제외 {len(unopened_stores)}개" if unopened_stores else ""

    generated_at = pd.Timestamp.now(tz="Asia/Seoul").strftime("%Y-%m-%d %H:%M")
    payload = json.dumps(data, ensure_ascii=False, indent=2)
    content = (
        "// AUTO-GENERATED by Sales_Employee_Extract_Dags — 직접 수정 금지\n"
        f"window.EMPLOYEE_ACCOUNTS_GENERATED_AT = '{generated_at}';\n"
        f"window.EMPLOYEE_ACCOUNTS = {payload};\n"
    )

    try:
        ACCOUNTS_DATA_PATH.write_text(content, encoding="utf-8")
    except (PermissionError, OSError) as exc:
        logger.warning(
            "[계정 export] accounts_data.js 저장 스킵(권한/미마운트): %s (%s)",
            ACCOUNTS_DATA_PATH,
            exc,
        )
        return (
            f"⚠️ accounts_data.js 저장 스킵(권한/미마운트): {ACCOUNTS_DATA_PATH} — "
            f"담당자 {manager_count}명 / 계정 {coupang_count}개{unopened_note}"
        )

    return (
        f"✅ accounts_data.js 생성: 담당자 {manager_count}명 / "
        f"계정 {coupang_count}개 (쿠팡 {coupang_count}){unopened_note}"
    )
